### ISSUE TITLE
Sugestões de melhorias na legibilidade do script

### ISSUE THREAD

**Issue by rafahsena** [DouglasBomfim/PokeCards#2]
Levando em consideração o arquivo script.js no commit 6193640, deixo abaixo algumas sugestões que podem que podem ajudar a deixar o código mais legível:

* Trocar as variáveis cards_body e options para const. Isso deixa claro que em todo o script o objeto será o mesmo.
* Na função get_evolution você pode usar um response.chain.evolves_to.find() pra encontrar a evolução desejada ao invés dos dois forEach's. Ainda nessa função, recomendo nomes de variáveis mais descritivos (e.g firstEvolution ao invés de element1). Fica bem mais fácil de entender o código se os nomes das variáveis deixarem explícito o que está guardado ali.
* Na função populate o id="random_button" não faz sentido, já que esse id não será único.

**Comment by DouglasBomfim** [comment]
Considerando suas recomendações, vejo que você compreendeu errado o que é feito na função get_evolution. Se observarmos o resultado dos requests, temos uma árvore, e o resultado buscado são os filhos da chave onde a chave corresponde com o valor nome passado como parâmetro, com o find basicamente acharíamos a chave somente, por isso foi escolhido essa abordagem (não é a melhor solução possível, mas a mais tranquila a se fazer sabendo previamente que a arvóre somente chega a dois níveis se considerarmos a partir dos filhos). No mais, as outras sugestões foi seguidas no commit 9dce625.

**Comment by rafahsena** [comment]
De fato, utilizar o find() geraria um comportamento diferente do esperado, foi um equívoco meu.
